(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self,m=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var ba,p;a:{for(var ca=["CLOSURE_FLAGS"],q=l,da=0;da<ca.length;da++)if(q=q[ca[da]],null==q){p=null;break a}p=q}var ea=p&&p[610401301];ba=null!=ea?ea:!1;var r;const fa=l.navigator;r=fa?fa.userAgentData||null:null;function ha(a){return ba?r?r.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function t(a){var b;a:{if(b=l.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function u(){return ba?!!r&&0<r.brands.length:!1}function ja(){return u()?ha("Chromium"):(t("Chrome")||t("CriOS"))&&!(u()?0:t("Edge"))||t("Silk")};const ka=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){const c=a.length,d=Array(c),f="string"===typeof a?a.split(""):a;for(let e=0;e<c;e++)e in f&&(d[e]=b.call(void 0,f[e],e,a));return d};var la=u()?!1:t("Trident")||t("MSIE");!t("Android")||ja();ja();t("Safari")&&(ja()||(u()?0:t("Coast"))||(u()?0:t("Opera"))||(u()?0:t("Edge"))||(u()?ha("Microsoft Edge"):t("Edg/"))||u()&&ha("Opera"));var ma={},v=null;var na="undefined"!==typeof Uint8Array;const oa=!la&&"function"===typeof l.btoa;const w="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;function x(a,b){if(w)return a[w]|=b;if(void 0!==a.h)return a.h|=b;Object.defineProperties(a,{h:{value:b,configurable:!0,writable:!0,enumerable:!1}});return b}function y(a){let b;w?b=a[w]:b=a.h;return null==b?0:b}function z(a,b){w?a[w]=b:void 0!==a.h?a.h=b:Object.defineProperties(a,{h:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a}function pa(a){x(a,1);return a}function qa(a){x(a,16);return a}
function ra(a,b){z(b,(a|0)&-51)}function A(a,b){z(b,(a|18)&-41)};var C={};function sa(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let ta;var D=Object.freeze(z([],23));function E(a){if(y(a.i)&2)throw Error();}function ua(a){var b=a.length;(b=b?a[b-1]:void 0)&&sa(b)?b.g=1:a.push({g:1})};function va(a,b){const c=y(a);let d=c;0===d&&(d|=b&16);d|=b&2;d!==c&&z(a,d)};var wa=function(a){const b=a.l+a.m;return a.j||(a.j=a.i[b]={})},F=function(a,b,c){return-1===b?null:b>=a.l?a.j?a.j[b]:void 0:c&&a.j&&(c=a.j[b],null!=c)?c:a.i[b+a.m]},G=function(a,b,c,d){a.o&&(a.o=void 0);if(b>=a.l||d)return wa(a)[b]=c,a;a.i[b+a.m]=c;(c=a.j)&&b in c&&delete c[b];return a},K=function(a,b,c){return void 0!==H(a,b,I(a,J,c))};function xa(a,b,c){a=F(a,b);Array.isArray(a)||(a=D);b=y(a);b&1||pa(a);c&&(b&2||x(a,18));return a}var L=function(a,b){a=F(a,b);a=null==a?a:!!a;return null==a?!1:a};
function ya(a,b,c,d){E(a);c!==d?G(a,b,c):G(a,b,void 0,!1);return a}
var I=function(a,b,c){return M(a,b)===c?c:-1},M=function(a,b){let c=0;for(let d=0;d<b.length;d++){const f=b[d];null!=F(a,f)&&(0!==c&&G(a,c,void 0,!1),c=f)}return c},H=function(a,b,c,d){const f=F(a,c,d);{let e=!1;null==f||"object"!==typeof f||(e=Array.isArray(f))||f.s!==C?e?(va(f,y(a.i)),b=new b(f)):b=void 0:b=f}b!==f&&null!=b&&G(a,c,b,d);return b},N=function(a,b,c){b=H(a,b,c,!1);if(null==b)return b;if(!(y(a.i)&2)){const d=za(b);d!==b&&(b=d,G(a,c,b,!1))}return b},Ba=function(a,b){var c=y(a.i),d=!!(c&
2);var f=d?1:2;var e=!!(c&2);a.h||(a.h={});var g=a.h[b],h=xa(a,b,e);if(g)3===f||e||((e=Object.isFrozen(g),1!==f||e)?2===f&&e&&(g=Array.prototype.slice.call(g),a.h[b]=g):Object.freeze(g)),f=g;else{var k=h,n=Aa;g=[];e=!!(c&2);h=!!(y(k)&2);const ab=k;!e&&h&&(k=Array.prototype.slice.call(k));var U=c|(h?2:0);c=h;let ia=0;for(;ia<k.length;ia++){var B=k[ia];var bb=n;Array.isArray(B)?(va(B,U),B=new bb(B)):B=void 0;void 0!==B&&(c||(c=!!(2&y(B.i))),g.push(B))}a.h[b]=g;n=k;U=y(n);k=U|33;k=c?k&-9:k|8;U!=k&&(c=
n,Object.isFrozen(c)&&(c=Array.prototype.slice.call(c)),z(c,k),n=c);k=n;ab!==k&&G(a,b,k);(e||1===f&&h)&&x(g,18);(e||1===f)&&Object.freeze(g);f=g}a=xa(a,b,d);if(!(d||y(a)&8)){for(d=0;d<f.length;d++)b=f[d],g=za(b),b!==g&&(f[d]=g,a[d]=g.i);x(a,8)}return f},O=function(a,b){a=F(a,b);return null==a?0:a},P=function(a,b){a=F(a,b);return null==a?"":a};let Q;function Ca(a,b){Q=b;a=new a(b);Q=void 0;return a};function Da(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a)if(Array.isArray(a)){if(0!==(y(a)&128))return a=Array.prototype.slice.call(a),ua(a),a}else if(na&&null!=a&&a instanceof Uint8Array){if(oa){for(var b="";10240<a.length;)b+=String.fromCharCode.apply(null,a.subarray(0,10240)),a=a.subarray(10240);b+=String.fromCharCode.apply(null,a);a=btoa(b)}else{void 0===b&&(b=0);if(!v){v={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),
d=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var e=c.concat(d[f].split(""));ma[f]=e;for(var g=0;g<e.length;g++){var h=e[g];void 0===v[h]&&(v[h]=g)}}}b=ma[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(f=e=0;e<a.length-2;e+=3){var k=a[e],n=a[e+1];h=a[e+2];g=b[k>>2];k=b[(k&3)<<4|n>>4];n=b[(n&15)<<2|h>>6];h=b[h&63];c[f++]=""+g+k+n+h}g=0;h=d;switch(a.length-e){case 2:g=a[e+1],h=b[(g&15)<<2]||d;case 1:a=a[e],c[f]=""+b[a>>2]+b[(a&3)<<4|g>>4]+h+d}a=c.join("")}return a}}return a};function Ea(a,b,c,d,f){if(null!=a){if(Array.isArray(a))a=f&&0==a.length&&y(a)&1?void 0:Fa(a,b,c,void 0!==d,f);else if(sa(a)){const e={};for(let g in a)e[g]=Ea(a[g],b,c,d,f);a=e}else a=b(a,d);return a}}function Fa(a,b,c,d,f){const e=y(a);d=d?!!(e&16):void 0;a=Array.prototype.slice.call(a);for(let g=0;g<a.length;g++)a[g]=Ea(a[g],b,c,d,f);c(e,a);return a}function Ga(a){return a.s===C?a.toJSON():Da(a)}function Ha(a,b){a&128&&ua(b)};function Ia(a,b,c=A){if(null!=a){if(na&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){const d=y(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return z(a,d|18),a;a=Fa(a,Ia,d&4?A:c,!0,!1);b=y(a);b&4&&b&2&&Object.freeze(a);return a}return a.s===C?Ja(a):a}}
function Ka(a,b,c,d,f,e,g){if(a=a.h&&a.h[c]){d=y(a);d&2?d=a:(e=ka(a,Ja),A(d,e),Object.freeze(e),d=e);E(b);g=null==d?D:pa([]);if(null!=d){e=!!d.length;for(a=0;a<d.length;a++){const h=d[a];e=e&&!(y(h.i)&2);g[a]=h.i}e=(e?8:0)|1;a=y(g);(a&e)!==e&&(Object.isFrozen(g)&&(g=Array.prototype.slice.call(g)),z(g,a|e));b.h||(b.h={});b.h[c]=d}else b.h&&(b.h[c]=void 0);G(b,c,g,f)}else d=Ia(d,e,g),E(b),G(b,c,d,f)}function Ja(a){if(y(a.i)&2)return a;a=La(a,!0);x(a.i,18);return a}
function La(a,b){const c=a.i;var d=qa([]),f=a.constructor.h;f&&d.push(f);f=a.j;if(f){d.length=c.length;var e={};d[d.length-1]=e}0!==(y(c)&128)&&ua(d);b=b||y(a.i)&2?A:ra;d=Ca(a.constructor,d);a.u&&(d.u=a.u.slice());e=!!(y(c)&16);const g=f?c.length-1:c.length;for(let h=0;h<g;h++)Ka(a,d,h-a.m,c[h],!1,e,b);if(f)for(const h in f)Ka(a,d,+h,f[h],!0,e,b);return d}function za(a){if(!(y(a.i)&2))return a;const b=La(a,!1);b.o=a;return b};var R=class{constructor(a,b,c){null==a&&(a=Q);Q=void 0;var d=this.constructor.h;if(null==a){a=d?[d]:[];var f=!0;z(a,48)}else{if(!Array.isArray(a))throw Error();if(d&&d!==a[0])throw Error();var e=x(a,0)|32;f=0!==(16&e);if(128&e)throw Error();z(a,e)}this.m=d?0:-1;this.h=void 0;this.i=a;a:{e=this.i.length;d=e-1;if(e&&(e=this.i[d],sa(e))){this.j=e;this.l=d-this.m;break a}void 0!==b&&-1<b?(this.l=Math.max(b,d+1-this.m),this.j=void 0):this.l=Number.MAX_VALUE}if(this.j&&"g"in this.j)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');
if(c){b=f&&!0;f=this.l;let h;for(d=0;d<c.length;d++)if(e=c[d],e<f){e+=this.m;var g=a[e];g?Ma(g,b):a[e]=D}else h||(h=wa(this)),(g=h[e])?Ma(g,b):h[e]=D}}toJSON(){const a=this.i;var b;ta?b=a:b=Fa(a,Ga,Ha,void 0,!1);return b}};function Ma(a,b){if(Array.isArray(a)){var c=y(a),d=1;!b||c&2||(d|=16);(c&d)!==d&&z(a,c|d)}}R.prototype.s=C;R.prototype.toString=function(){return this.i.toString()};function Na(a,b){return Da(b)};var Aa=class extends R{constructor(a){super(a)}},S=[2,3,4];var T=class extends R{constructor(a){super(a)}};var V=class extends R{constructor(a){super(a)}};var Pa=class extends R{constructor(a){super(a,-1,Oa)}},Oa=[6];var Qa=class extends R{constructor(){super()}};var Ra=class extends R{constructor(){super()}},Sa=[2];var Ua=class extends R{constructor(a){super(a,-1,Ta)}},Ta=[2];var Va=class extends R{constructor(a){super(a)}};var Wa=class extends R{constructor(a){super(a)}};var Xa=class extends R{constructor(a){super(a)}};var Ya=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);b=Ca(a,qa(b))}return b}}(class extends R{constructor(a){super(a)}}),J=[2,3,4,5,6,7];var W;var cb=function(a,b){this.l=a===Za&&b||"";this.h=$a},$a={},Za={};var eb=class{constructor(a,b){this.h=b===db?a:""}toString(){return this.h+""}},db={};var fb=function(){this.h=document||{cookie:""}};
fb.prototype.set=function(a,b,c){let d,f,e,g=!1,h;"object"===typeof c&&(h=c.B,g=c.C||!1,e=c.domain||void 0,f=c.path||void 0,d=c.A);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.h.cookie=a+"="+b+(e?";domain="+e:"")+(f?";path="+f:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(g?";secure":"")+(null!=h?";samesite="+h:"")};
fb.prototype.get=function(a,b){const c=a+"=",d=(this.h.cookie||"").split(";");for(let f=0,e;f<d.length;f++){e=aa(d[f]);if(0==e.lastIndexOf(c,0))return e.slice(c.length);if(e==a)return""}return b};/*

 SPDX-License-Identifier: Apache-2.0
*/
class gb{constructor(){this.l=new fb;this.h="";this.o=a=>{a:{let k;try{k=Ya(a.data)}catch(n){break a}if(K(k,Pa,4)){var b=N(k,Pa,I(k,J,4)),c=Ba(b,6),d;c.length&&(d=hb(c));c={event:P(b,1)||void 0,category:P(b,2)||void 0,action:P(b,3)||void 0,label:P(b,4)||void 0,value:O(b,5)||void 0,nonInteraction:L(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==H(b,V,12,!1)){var f=N(b,V,12);c.recommendations={targetPage:P(f,1),targetType:O(f,2),targetRank:O(f,3),targetIdenticalDescriptions:O(f,4),targetTitleWords:O(f,
5),targetDescriptionWords:O(f,6),experiment:P(f,7)};d="";for(var e of window.dataLayer)if("experiment"in e&&"baseIds"in e.experiment){d=e.experiment.baseIds;break}(d=ib(d,P(f,7)))&&L(f,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var g of window.dataLayer)if("experiment"in g&&"ids"in g.experiment&&g.experiment.ids){c.experiment=
{ids:g.experiment.ids};break}e=N(b,T,11);if(void 0!==H(b,T,11,!1)&&null!==e){b=jb(e);for(var h of Object.keys(b))c[h]=b[h]}window.dataLayer.push(c)}else if(K(k,Ua,3)){b=N(k,Ua,I(k,J,3));c=Ba(b,2);let n;c.length&&(n=hb(c));c={event:"trackPageview",pageName:P(b,1),additionalParams:n||void 0,nonInteraction:L(b,3)||void 0,ratingsCount:O(b,4)||void 0,ratingsValue:O(b,5)||void 0};h=N(b,T,6);if(void 0!==H(b,T,6,!1)&&null!==h){b=jb(h);for(f of Object.keys(b))c[f]=b[f]}window.dataLayer.push(c)}else if(K(k,
Va,7))b=N(k,Va,I(k,J,7)),window.dataLayer.push({parentContext:{referrer:P(b,2)||"",_ga_devsiteCookie:P(b,1)||""}});else if(K(k,Wa,6))b=N(k,Wa,I(k,J,6)),c=this.h,h=N(b,V,9)||new V,e=P(b,10)||void 0,b={experiment:{ids:(L(h,8)?ib(e,P(h,7)):e)||void 0,baseIds:e||void 0},hostContext:{internalUser:P(b,1)||void 0,pageType:P(b,8)||void 0,projectName:P(b,6)||void 0,signedIn:P(b,2)||void 0,tenant:P(b,5)||void 0,thirdPartyCookieAccepted:c.length?"True":"False"},language:{machineTranslated:P(b,7)||void 0,requested:P(b,
3)||void 0,served:P(b,4)||void 0},recommendations:{sourcePage:P(h,1),sourceType:O(h,2),sourceRank:O(h,3),sourceIdenticalDescriptions:O(h,4),sourceTitleWords:O(h,5),sourceDescriptionWords:O(h,6),experiment:P(h,7)}},window.dataLayer.push(b);else if(K(k,Xa,5))b=N(k,Xa,I(k,J,5)),window.dataLayer.push({originalUrlParameters:{dclid:P(b,1)||void 0,gclid:P(b,2)||void 0,utmCampaign:P(b,3)||void 0,utmContent:P(b,4)||void 0,utmCreativeFormat:P(b,8)||void 0,utmMarketingTactic:P(b,10)||void 0,utmMedium:P(b,5)||
void 0,utmSource:P(b,6)||void 0,utmSourcePlatform:P(b,9)||void 0,utmTerm:P(b,7)||void 0}});else if(2===M(k,J)){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"});h=document.getElementsByTagName("script")[0];e=document.createElement("script");e.async=!0;g=new cb(Za,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");g=g instanceof cb&&g.constructor===cb&&g.h===$a?g.l:"type_error:Const";if(void 0===W)if(f=null,(d=l.trustedTypes)&&d.createPolicy){try{f=
d.createPolicy("goog#html",{createHTML:m,createScript:m,createScriptURL:m})}catch(n){l.console&&l.console.error(n.message)}W=f}else W=f;g=(f=W)?f.createScriptURL(g):g;f=new eb(g,db);g=e;g.src=f instanceof eb&&f.constructor===eb?f.h:"type_error:TrustedResourceUrl";(b=(f=null==(c=(b=(g.ownerDocument&&g.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]"))?f.nonce||f.getAttribute("nonce")||"":"")&&g.setAttribute("nonce",b);h.parentNode.insertBefore(e,h)}}};window.addEventListener("message",
this.o)}v(a){this.h=this.l.get("_ga_devsite")||"";var b=new Qa;a=ya(b,1,null==a?a:!!a,!1);b=ya(a,2,this.h,"");a=new Ra;E(a);null==b&&(b=void 0);E(a);var c=M(a,Sa);c&&2!==c&&null!=b&&G(a,c,void 0,!1);a=G(a,2,b);if(window.parent!==window){b=window.parent;c=b.postMessage;a:{ta=!0;try{var d=JSON.stringify(a.toJSON(),Na);break a}finally{ta=!1}d=void 0}c.call(b,d,"*")}}}gb.prototype.notifyIframeReady=gb.prototype.v;
function hb(a){const b={};for(const c of a){a=P(c,1);let d;P(c,I(c,S,2))?d=P(c,I(c,S,2)):O(c,I(c,S,3))?d=O(c,I(c,S,3)):4===M(c,S)&&(d=L(c,I(c,S,4))?"True":"False");b[a]=d}return b}
function jb(a){const b={};if(!a)return b;b.hasProfile=L(a,6)?"True":"False";b.practitionerType=P(a,1)||"Property not set";b.profileCreationMethod=P(a,4)||"Property not set";b.profileHasInterests=L(a,12)?"True":"False";b.profileInterests=P(a,13)||"Property not set";b.profileHasJobTitle=L(a,10)?"True":"False";b.profileHasLocation=L(a,7)?"True":"False";b.profileHasPronoun=L(a,9)?"True":"False";b.profileIsPublic=L(a,8)?"True":"False";b.profileSocialLinks=P(a,11)||"Property not set";b.profileBadgeEmailOptIn=
L(a,5)?"True":"False";b.profileFeedbackEmailOptIn=L(a,2)?"True":"False";b.profileNewsletterEmailOptIn=L(a,3)?"True":"False";return b}function ib(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var kb=gb,X=["AnalyticsLibrary"],Y=l;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===kb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=kb;}).call(this);
