(function(_ds){var window=this;var sT=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},tT=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},uT=function(a){a=a.Dr;a=_ds.fA(new _ds.bA("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.V(_ds.sq(1)),XXX_2:_ds.V(_ds.sq(a))});return(0,_ds.T)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var vT="onpointerover"in window?"pointerover":"mouseover",wT=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.D(a,"visually-hidden","",c))},ET=function(a){a.eventHandler.listen(a,"click",b=>void xT(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&xT(a,b)});a.eventHandler.listen(a,[vT,"focusin"],b=>void yT(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.j&&(zT(a,"_book")?a.removeAttribute("top-level-nav"):_ds.D(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.J.Ba());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.J.Ba()});a.eventHandler.listen(a,"scroll",()=>{_ds.D(a,"user-scrolled","")});a.eventHandler.listen(a.vb,"click",()=>{AT(a)});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.O.Ba()),a.eventHandler.listen(a.h,"focus",()=>void BT(a,"focus")));a.F&&a.eventHandler.listen(a.F,["click",
"keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.h&&(a.h.value="",a.h.focus());let c;null==(c=a.F)||c.classList.add("hidden");CT(a);DT(a);BT(a,b.type)}})},GT=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.D=new Set(b);if(!_ds.G().hash&&c)FT(a,a.D);else{c=new _ds.rI;for(const d of a.D)_ds.qI(c,d)}},HT=async function(a){const b=await _ds.x();for(const c of a.D)b.unregisterIntersectionForElement(c)},xT=function(a,b){if(!b.defaultPrevented){var c=b.target;
"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.D(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&zT(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.D(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.j&&(d=a.j.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},yT=function(a,b){b.defaultPrevented||(b=_ds.aj(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.jd(b,_ds.Ad(_ds.Yj(b.href).href)))},AT=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.wl(a.eventHandler,a,_ds.Sf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.v.removeAttribute("animatable")});_ds.D(a,"animatable","");b=_ds.nd(a.o`animatable`);b(a.background,"animatable","");b(a.v,"animatable","");a.hasAttribute("collapsed")?(_ds.D(a,"aria-expanded","true",a.vb),_ds.D(a,"aria-label","Hide side navigation",a.vb),_ds.D(a,"data-title","Hide side navigation",a.vb),a.removeAttribute("collapsed"),IT(a,
"Expanded book nav")):(a.vb.removeAttribute("aria-expanded"),_ds.D(a,"aria-label","Show side navigation",a.vb),_ds.D(a,"data-title","Show side navigation",a.vb),_ds.D(a,"collapsed",""),IT(a,"Collapsed book nav"));await _ds.fk();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},BT=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===
b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},JT=function(a){a.G=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},LT=function(a){const b=_ds.G().searchParams.get("nf");a.h&&b&&(a.h.value=b,KT(a))},KT=function(a){if(a.G.length){CT(a);DT(a);var b,c,d=null==(b=a.h)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.F)||e.classList.remove("hidden");
for(const g of a.G){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");
let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.ld(f,_ds.yh.h(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.O(uT,{Dr:a}),b.appendChild(a))}}else null==(f=a.F)||f.classList.add("hidden")}},CT=function(a){for(const b of a.G){let c;b.classList.toggle("hidden",!(null==(c=a.h)||!c.value))}},DT=function(a){if(a.querySelector("mark")){var b=
[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.ld(a,_ds.yh.h(b))}}},FT=async function(a,b){if(a.C){var c=await _ds.x(),d=new _ds.rI,e=f=>{f=f.target;_ds.qI(d,f);a.D.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},zT=
function(a,b){let c=!1;if(a.j)for(const d of a.j.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.D(a,"hidden","",d);return c},MT=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.mk(_ds.G().pathname);a=`[href="${_ds.Yj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},NT=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},PT=async function(a){a.C&&(a.removeAttribute("user-scrolled"),await _ds.fk(),await OT(a),await a.W,await _ds.x(),await _ds.fk(),await OT(a))},
OT=async function(a){if(a.C&&a.j){await _ds.x();var b=a.j.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await QT(a,b))}},QT=async function(a,b){if(a.C){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Ml(b,a,!0).y;await _ds.fk();c&&_ds.D(a,"user-scrolled","")}},IT=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},RT=class extends _ds.F{static get observedAttributes(){return["collapsed",
"fixed","hidden"]}constructor(){super();this.C=!1;this.F=this.h=this.H=this.j=null;this.G=[];this.eventHandler=new _ds.H;this.M=()=>{};this.D=new Set;this.K=this.V=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.vb=_ds.O(sT);this.v=_ds.O(tT);this.W=new Promise(a=>{this.M=a});this.J=new _ds.sl(()=>{this.C&&wT(this)},20);this.O=new _ds.sl(()=>{KT(this)},20)}async connectedCallback(){this.C=!0;_ds.Fh(this,this.o`animatable`,this.o`aria-expanded`,
this.o`aria-label`,this.o`collapsed`,this.o`data-title`,this.o`fixed`,this.o`has-book-nav`,this.o`hidden`,this.o`top-level-nav`,this.o`user-scrolled`,this.o`visually-hidden`);_ds.Ji(this.background,this);this.hasAttribute("hidden")&&(_ds.D(this,"hidden","",this.vb),_ds.D(this,"hidden","",this.v));const a=await _ds.x();if(this.V=a.hasMendelFlagAccess("BookNav","enable_collapsible_book_nav")){let b;null==(b=this.parentElement)||b.insertBefore(this.vb,this.nextSibling);_ds.D(this,"aria-label","Hide side navigation",
this.vb);_ds.D(this,"data-title","Hide side navigation",this.vb);_ds.D(this,"aria-expanded","true",this.vb);let c;null==(c=this.parentElement)||c.insertBefore(this.v,this.nextSibling)}if(this.K=a.hasMendelFlagAccess("BookNav","enable_book_nav_filtering"))if(this.H=this.querySelector(".devsite-book-nav-filter"))this.h=this.H.querySelector("input[type=text]"),this.F=this.H.querySelector(".filter-clear-button"),JT(this),LT(this);wT(this);ET(this);await this.init();GT(this)}disconnectedCallback(){this.C=
!1;_ds.I(this.eventHandler);HT(this);this.D.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.D(this,"visually-hidden","",a);a=[this.background,this.vb,this.v];for(const b of a)b&&_ds.Li(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.v.removeAttribute("animatable");this.v.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.D(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.vb,this.v];for(const d of c)d&&(b?_ds.D(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.M()}async init(a=!0){if(this.C){this.v.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.j=this.querySelector(".devsite-mobile-nav-bottom");_ds.D(this,"top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.D(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.D(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(MT(this),NT(this),await PT(this)):(await _ds.fk(),await OT(this))}}async wb(a){a?(a=a.querySelector("nav")||
null,MT(this,a),NT(this,a),a&&(await HT(this),this.D.clear(),GT(this,a,!1)),_ds.Ih(this,this.querySelector("nav"),a)):_ds.Ii(this);if(this.K&&(JT(this),this.h)){this.h.value="";let b;null==(b=this.F)||b.classList.add("hidden");LT(this)}await _ds.fk();await this.init(!1)}};RT.prototype.updateContent=RT.prototype.wb;RT.prototype.attributeChangedCallback=RT.prototype.attributeChangedCallback;RT.prototype.disconnectedCallback=RT.prototype.disconnectedCallback;RT.prototype.connectedCallback=RT.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",RT)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
