(function(_ds){var window=this;var o8=function(a){const b=a.Ws,c=a.tc,d=a.Xp;a=a.ir;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.VF("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=b[h];e+='<li class="devsite-nav-item"'+
(c&&g.index<a?" visible":"")+'><a href="#'+_ds.Y(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+'" track-metadata-link-destination="#'+_ds.Y(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(g.text)+"</span></a>";if(_ds.W(g.children).length){e+='<ul class="devsite-nav-list">';
g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.Y(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-metadata-link-destination="#'+
_ds.Y(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.VF("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.T)(e+"</ul>")};var q8=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.tc?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),p8(a,b),a.H=!0):a.bb()}},s8=async function(a){await r8(a);if(a.h){var b=`#${a.h.id}`,c=encodeURI(b);b=a.F.get(b)||a.F.get(c);a.v!==b&&(a.v&&a.v.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.v=b))}},t8=function(a){a.tc||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
()=>{a.M.Ba()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{q8(a)})},u8=async function(a){if("IntersectionObserver"in _ds.Ci()){a.C&&a.C.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await window.customElements.whenDefined("devsite-header"),(b=Number(b.getAttribute("top-row--height"))+Number(b.getAttribute("bottom-row--height")))&&(c=b));a.C=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.D.add(e.target):a.D.delete(e.target);a.M.Ba()},
{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.J.h()},r8=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),b=c.C());c=a.j.findIndex(e=>a.D.has(e)&&e.getBoundingClientRect().top>=b);const d=a.j[c];if(d){const e=await v8();d.getBoundingClientRect().top-b>e&&0<c?a.h=a.j[c-1]:a.h=d}else a.h&&a.h.getBoundingClientRect().top>window.innerHeight&&(c=a.j.indexOf(a.h),0<c&&(a.h=a.j[c-1]))},p8=function(a,b){const c=[];
let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.j=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>w8(f));for(const [f,g]of a.j.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-
1].children.push(b):c.push(b);_ds.zb(a.G,c,a.K.bind(a))&&a.H||(c.length?(x8(a,c),a.show(),a.tc||y8(a)):a.bb(),a.G=c)},w8=function(a){return _ds.tk.find(b=>!!_ds.bj(a,null,b,6))||_ds.bj(a,"devsite-selector",null,6)||_ds.bj(a,null,"devsite-dialog",3)?!1:!0},x8=function(a,b){const c=_ds.O(o8,{Ws:b,tc:a.tc,Xp:!!document.body.querySelector("devsite-apix, .devsite-apix"),ir:8>b.length?8:5});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.F.set(e,b);
a.F.set(f,b)}_ds.Ii(a);a.tc&&_ds.D(a,"hidden","",c);a.appendChild(c);if(a.tc){if(8<a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.D(a,"expanded","")});_ds.D(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},0)}},y8=async function(a){await a.J.promise;if(a.C){a.C.disconnect();
a.D.clear();a.v&&a.v.classList.remove("devsite-nav-active");a.v=null;for(const b of a.j)a.C.observe(b)}},v8=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await window.customElements.whenDefined("devsite-header"),a=c.C(),b=c.J());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},z8=class extends _ds.F{static get observedAttributes(){return["max-height","offset"]}constructor(){super();this.eventHandler=new _ds.H;this.J=new _ds.yl;this.D=new Set;this.F=new Map;
this.V=new _ds.sl(()=>void q8(this),16);this.M=new _ds.sl(()=>void s8(this),33);this.h=this.v=null;this.j=[];this.H=!1;this.C=null;this.tc=!1;this.G=[];_ds.Fh(this,(0,_ds.v)`disabled`,(0,_ds.v)`has-sidebar`,(0,_ds.v)`hidden`,(0,_ds.v)`expandable`,(0,_ds.v)`expanded`,(0,_ds.v)`visible`)}connectedCallback(){this.tc=this.hasAttribute("devsite-toc-embedded");q8(this);t8(this)}disconnectedCallback(){this.bb();this.H=!1;_ds.I(this.eventHandler)}Ch(a){a=a&&"false"===a.toLowerCase();this.G=[];_ds.Ii(this);
a?(_ds.D(this,"disabled",""),this.bb()):(this.removeAttribute("disabled"),this.show(),this.V.Ba())}bb(){_ds.Ii(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.D(this,"hidden","");if(!this.tc){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.D(this,"visible","");if(!this.tc){const a=
document.querySelector(".devsite-main-content");a&&_ds.D(this,"has-sidebar","",a);u8(this)}}K(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.zb(a.children,b.children,this.K.bind(this));return c&&a.id===b.id&&a.text===b.text}};z8.prototype.renderUpdatedContent=z8.prototype.Ch;z8.prototype.disconnectedCallback=z8.prototype.disconnectedCallback;z8.prototype.connectedCallback=z8.prototype.connectedCallback;try{window.customElements.define("devsite-toc",z8)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
