(function(_ds){var window=this;var jZ=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.Cl(a,iZ(),b)},iZ=_ds.Rh(function(){return _ds.Ge&&9==_ds.af?"-ms-transform":"transform"});var mZ=function(a){a.j=kZ(a,".devsite-top-logo-row-wrapper-wrapper");a.h=kZ(a,".devsite-collapsible-section");a.v=kZ(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.h}`);a.setAttribute("bottom-tabs--height",`${a.v}`);lZ(a)},lZ=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.h-a.v&&a.hasAttribute("bottom-row--hidden")&&
a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.G&&(_ds.Cl(b,"transform",`translate3d(0, -${a.offset}px, 0)`),nZ(a),a.G=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.C()}px`)},oZ=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.H);a.D&&window.cancelAnimationFrame(a.D);c.removeAttribute("transition");a.removeAttribute("search-expanded");
var e=new _ds.di(b.offsetWidth,b.offsetHeight);b=new _ds.di(c.offsetWidth,c.offsetHeight);var f=_ds.Vl(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Cl(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});jZ(c,a.hasAttribute("search-active")?0:e);_ds.wl(a.H,d,_ds.Sf,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");
n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),jZ(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.D=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.Cl(d,iZ(),m);jZ(c,k)})}},pZ=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");
var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.fk(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled","")))}},rZ=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.ma;_ds.bj(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});
a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>qZ(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{qZ(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},sZ=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},nZ=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},qZ=function(a){window.requestAnimationFrame(()=>
a.K.Ba())},kZ=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},tZ=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},uZ=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Ih(a,c,b))},vZ=class extends _ds.F{constructor(){super(...arguments);this.eventHandler=new _ds.H;this.G=
-1;this.H=new _ds.H;this.D=0;this.F=new MutationObserver(()=>mZ(this));this.K=new _ds.sl(()=>{mZ(this);nZ(this)},15);this.authUser=void 0;this.offset=this.v=this.h=this.j=0;this.updated=!1}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;lZ(this);break;case "search-active":oZ(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),
c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),pZ(this,a)}}connectedCallback(){rZ(this);sZ(this);nZ(this);mZ(this);this.F.observe(this,{childList:!0,subtree:!0});lZ(this);const a=_ds.G();this.authUser=_ds.Fj(_ds.Gj(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.F.disconnect()}C(){return this.j+this.h-this.offset}J(){return this.j+this.h}wb(a){this.updated=!1;if(a){uZ(this,a,".devsite-header-upper-tabs");
uZ(this,a,".devsite-collapsible-section");uZ(this,a,".devsite-product-name-wrapper");uZ(this,a,"devsite-language-selector");uZ(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&tZ(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(tZ(c,b),c=_ds.G(),c=_ds.Fj(_ds.Gj(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Ih(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),
this.querySelector(".devsite-top-logo-row-middle"));_ds.Ih(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Ii(this),this.appendChild(a));sZ(this);qZ(this)}};try{window.customElements.define("devsite-header",vZ)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
