(function(_ds){var window=this;var DV=function(a){return!a.classList.contains("material-icons")},LV=async function(a,b){await DevsiteApp.whenReady();const c=_ds.G();var d=DevsiteApp.getInsecureHost();b=b.ma;if(b.origin===c.origin||!d||b.origin===d){try{var e=(0,_ds.um)(b.data)}catch(g){return}d=_ds.Ef(e,1);if(4===d)EV(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:FV(e,f);break;case 8:GV(b,e,c);break;case 1:HV(b,e,c);break;case 6:case 7:IV(d,c,e);break;case 9:JV(a,e);
break;case 10:KV(e,c)}}}},PV=function(a){a.v=a.querySelector(".devsite-article-body");a.v&&(MV(a),a.C=[]);a.h&&a.h.disconnect();a.j.clear();NV(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.v&&(b=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.j.clear();a.j=new Set(c);if(_ds.G().hash){c=new _ds.rI;for(const d of a.j)_ds.qI(c,d,DV)}else OV(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},NV=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Ji(c,b);c.appendChild(b)}})},EV=async function(a,b){const c=QV(a,b.source);if(c){const e="goog_"+_ds.pi++;c.setAttribute("name",e);var d=_ds.sm(3);d=_ds.nc(d,2,e);(b=b.source)&&b.postMessage(_ds.Hf(d),"*");(b=document.body.getAttribute("appearance"))&&RV(c,b);a.C.push(c)}},FV=async function(a,b){const c=_ds.Bi(document).y,d=_ds.yf(a,4);a=_ds.yf(a,3);b=_ds.Ri(b);d&&b.setAttribute("width",
`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.Bi(document).x,c)})},GV=async function(a,b,c){b=_ds.tm(_ds.sm(8),_ds.z(b,8));c=_ds.nc(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.Hf(c),"*")},HV=async function(a,b,c){b=_ds.tm(_ds.sm(2),_ds.z(b,8));c=_ds.nc(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.Hf(c),"*")},IV=async function(a,b,c){const d=c.getTitle();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},JV=async function(a,b){const c=_ds.z(b,9);let d;try{d=JSON.parse(_ds.z(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",
{detail:d,bubbles:!0}))},KV=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},QV=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Si(d)===b&&(c=d)});return c},RV=function(a,b){var c=_ds.sm(12);b=_ds.nc(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.Hf(b),"*")},MV=function(a){"full"===
document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},OV=function(a,b){a.h&&b.forEach(c=>{a.h.observe(c)})},SV=class extends _ds.F{constructor(){super();this.D=new _ds.H;this.F=new _ds.H;this.j=new Set;this.C=[];this.h=null;"IntersectionObserver"in window&&(this.h=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&
(a=b.target,_ds.qI(new _ds.rI,a,DV),this.j.delete(a),this.h.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.D.listen(window,"message",a=>LV(this,a));this.D.listen(document.body,"devsite-appearance-updated",a=>{if((a=a.ma.detail.preference)&&this.C.length)for(const b of this.C)RV(b,a)});PV(this)}disconnectedCallback(){this.h&&this.h.disconnect();this.j.clear();_ds.I(this.D);_ds.I(this.F)}wb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>
{_ds.Ih(this,this.querySelector(b),a.querySelector(b))}),PV(this))}};SV.prototype.updateContent=SV.prototype.wb;SV.prototype.disconnectedCallback=SV.prototype.disconnectedCallback;SV.prototype.connectedCallback=SV.prototype.connectedCallback;try{window.customElements.define("devsite-content",SV)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
